### PR TITLE
Add SCS link  

### PR DESCRIPTION
**Pull request by mr-mos**
Blog article at Jobpushy: https://www.jobpushy.de/blog/11/self-contained-system-scs-%E2%80%94-architektur-trend

### CODE REVIEW

**Comment by stilkov** [comment]
Unfortunately, that article contains several misunderstandings, so we’re not inclined to link to it.

**Comment by mr-mos** [comment]
Let's discuss.  It's partly critical. But that shouldn't be the reason to refuse it, right?

**Comment by stilkov** [comment]
But it’s not a reason to include it, either.

The main beefs I have with that post are:

* It misses the point that SCS address with regards to UIs. An SPA is not a viable solution for a large-
scale effort as it’s inevitably going to turn into a monolith in its own right. The illusion of perfectly reusable backend services with front-end applications is exactly what SOA got wrong (and why it didn’t work out the way people hoped it would).
* Consistency in UIs can be addressed in an SCS environment using styleguides, shared assets, & pattern libraries. This is something that is actually being done in practice without downsides in terms of UI consistency – unless you count the fact that each SCS’s UI can evolve independently as a downside (we don’t)
* The SCS approach is used for large, public-facing sites. To claim it’s more suitable for internal enterprise apps is strange.

Anyway, it’s a perfectly fine opinion that anyone is entitled to. It would also (of course) be accepted as a comment for this site’s discussion page (as would a link (as a comment)).

**Comment by mr-mos** [comment]
Sure, another opinion (critics) isn't per se a reason to include a link. But it helps to get a broader discussion. :)
And by the way: Most of the article is a about defining a SCS and showing differences to SOA and Microservices.  That should be the reason.....

And yes regarding the UI integration of SCS I had different experiences in some of my customer projects. That's one of the most discussed parts about SCS, right?

Nevertheless, the SCS website is yours and it's totally fine if you don't wanna have articles with partly other viewpoints.

**Comment by stilkov** [comment]
While I appreciate the discussion, let’s not turn this into a never-ending story. To be clear, other viewpoints are fine, please do agree and disagree as you please – on your own blog, some other site, or in the comments & discussion section :-) We don’t want to include a link to articles in this section because we believe it may be interpreted as endorsement.

**Comment by mechanoid** [comment]
As I see it, the website contains mainly content, and also blog articles that describe the principles behind SCS or try to give an explanation on how to migrate to SCS. While I personally agree with you in that we should challenge and discuss this kind of architecture, I see it like @stilkov in that we should do that in the "Discussion" area on the website. 

Especially because I think, that personal opinions like "Eine Anwendungsarchitektur, die ein zentral implementiertes Frontend vorsieht, wird stets im Vorteil sein." or in english something like (please excuse my rough translation) "an architecture, that implements a central frontend will always have an advantage [...]" without further explanation should not be referenced in the Links section.

In my opinion we should discuss this topic, as we did with [Darcy Welsh](http://scs-architecture.org/discussion.html#comment-3114136187) and enrich the architecture with given outputs of that discussion.

**Pull request closed without merging**
