### PR TITLE
Layers vs. SCS added

### PR DESCRIPTION
**Pull request by ewolff**

### CODE REVIEW

**Comment by jochenchrist** [comment]
This PR is stale.
Is it still relevant?

**Comment by ewolff** [comment]
@jochenchrist I would like to merge it. I will do so on Monday. A review by you, @stilkov , and @mechanoid or any other person is highly welcomed!

**Comment by stilkov** [comment]
I suggest to make it a little clearer that the bad idea is to _split_ by layer. Otherwise people might end up thinking layering _within_ a service (or system) is a bad idea.

**Comment by jochenchrist** [comment]
I suggest a slightly different answer in #39

**Comment by martinweck** [comment]
has been replaced by https://github.com/innoq/SCS/pull/39

**Pull request closed without merging**
