### PR TITLE
fix the alignment of the footer text

### PR DESCRIPTION
**Pull request by niklas-heer**
Changes the appearance from:

bildschirmaufnahme vom 2017-06-21 17 39 35

to:

bildschirmaufnahme vom 2017-06-21 17 38 14

### CODE REVIEW

**Comment by mechanoid** [comment]
hey Niklas, thanks! Looks good to me. May we should re-insert some space for mobile view-ports, but your fix makes totally sense for now.

**Comment by mechanoid** [comment]
@niklas-heer FYI https://github.com/innoq/SCS/pull/28

**Comment by niklas-heer** [comment]
Thanks I thought about that, but didn't know if it was intended. ^^

**Comment by mechanoid** [comment]
Me neither :D Anyway, thanks again for your contributions! :)

**Comment by niklas-heer** [comment]
Hehe okay :D My pleasure! :)

**Pull request merged**
